#!/bin/bash
### BEGIN INIT INFO
# Provides: AirGraph
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

# This script modified the script below.
# Copyright (C) 2012-2014 Felix H. Dahlke
# Released under the MIT license
# https://github.com/fhd/init-script-template

user="sec"
dir="/home/${user}"
cmd="java -jar /opt/AirGraph/bin/airgraph.jar"

name=`basename $0`
pid_file="/opt/AirGraph/bin/$name.pid"
stdout_log="/opt/AirGraph/logs/$name.log"
stderr_log="/opt/AirGraph/logs/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            # TODO: Error
            source ${dir}/.bashrc
            sudo wasanbon-admin.py nameserver restart >> "$stdout_log" 2>> "$stderr_log" &
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            source ${dir}/.bashrc  >> "$stdout_log" 2>> "$stderr_log" &
            sudo -u "$user" wasanbon-admin.py nameserver restart  >> "$stdout_log" 2>> "$stderr_log" &
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in 1 2 3 4 5 6 7 8 9 10
        # for i in `seq 10`
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
